version: '3.7'

networks:
  expenses: { }

services:
  db:
    image: postgres
    volumes:
      - ./docker/postgres-multiple-databases.sh:/docker-entrypoint-initdb.d/postgres-multiple-databases.sh
    restart: always
    hostname: expense_control
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=expense_control,expense_control_test
    networks:
      - expenses

  app:
    container_name: expense_control_app
    ports:
      - 5000:5000
    image: "expense_control"
    restart: always
    depends_on:
      - db
    networks:
      - expenses