"""add name column to user

Revision ID: 59313135dcdd
Revises: 21d5318849d1
Create Date: 2019-11-03 19:39:00.465282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59313135dcdd'
down_revision = '21d5318849d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
