"""add expense category

Revision ID: 7279551116e9
Revises: ef6cd1e566e9
Create Date: 2021-07-25 10:35:12.973943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '7279551116e9'
down_revision = 'ef6cd1e566e9'
branch_labels = None
depends_on = None


def upgrade():
    expense_category = postgresql.ENUM('OTHER', 'FOOD', 'TRANSPORT', 'ENTERTAINMENT', name='expense_category')
    expense_category.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category', sa.Enum('OTHER', 'FOOD', 'TRANSPORT', 'ENTERTAINMENT', name='expense_category'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    expense_category = postgresql.ENUM('OTHER', 'FOOD', 'TRANSPORT', 'ENTERTAINMENT', name='expense_category')
    expense_category.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'category')
    # ### end Alembic commands ###
